# based on https://github.com/ulysseszh/ulysseszh/blob/master/.github/workflows/grs.yml
name: GitHub Readme Stats
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - master

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    name: Generate stats cards
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Generate stats
        uses: UlyssesZh/grs-action@7d6d316976be5912ac850de0d88a34364a144d44 # v0.2.5
        id: generate
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=onedark&hide=prs&show_icons=true&hide_rank=true&count_private=true
          path: grs/stats.svg
      - name: Upload stats
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: stats
          path: grs
  generate-langs:
    runs-on: ubuntu-latest
    name: Generate top language cards
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Generate stats
        uses: UlyssesZh/grs-action@7d6d316976be5912ac850de0d88a34364a144d44 # v0.2.5
        id: generate
        with:
          options: username=${{ github.repository_owner }}&layout=compact&theme=onedark&langs_count=6
          path: grs/langs.svg
          card: langs
      - name: Upload langs
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: langs
          path: grs
  push:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push
    needs: [generate-stats, generate-langs]
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: stats
          path: grs
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: langs
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        with:
          target_branch: grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
